### PR TITLE
Use application instead of activity to avoid duplicate applications s…

### PR DESCRIPTION
**Pull request by archie-sh**
…howing up in the task list
WhatsApp Image 2019-05-22 at 5 10 57 PM

### CODE REVIEW

**Comment by daadu** [comment]
I just checked the latest version. It still shows two screens (one for Flutter and another for Freshchat) on task-switcher in android.

**Comment by daadu** [comment]
I have  `MyApplication extends FlutterApplication`, it could be because of that?

**Comment by daadu** [comment]
Screenshot_1561163148

**Comment by daadu** [comment]
Now that I think of it, it is a good thing, User can chat with support as well as use the app, as they are different Task in andorid.

**Comment by daadu** [comment]
Could be helpful in case of mutli window environment

**Comment by archie-sh** [comment]
> I have `MyApplication extends FlutterApplication`, it could be because of that?

I cannot say without looking at your source code, maybe try with the example application included as part of the project, if that one shows two applications I will fix it.

> Now that I think of it, it is a good thing, User can chat with support as well as use the app, as they are different Task in andorid.

Apps like google chrome do not open different windows per tab or gmail does not open different windows per email. We could discuss if this is good or bad but the fact is users were reporting the two windows as a bug, not a feature. If you really think it should be a feature you can implement it so it is configurable through a boolean flag like the camera enable/disable.

**Pull request merged**
